### ISSUE TITLE
Autocomplete doesn't fill the search box

### ISSUE THREAD

**Issue by mbtomlinson** [Open-Seat-Philly/open-seat#7]
On selecting an address from the autocomplete box, the address is passed to the variable, but the search box doesn't fill with the selection.

**Comment by rzane** [comment]
You need to change the `value` of the Geocoder component in `onSelect`.

You'll want to change [this line](https://github.com/Open-Seat-Philly/open-seat/blob/master/src/components/Geocoder.js#L63) to `onSelect={this.handleSelect}`. Then, you'll want to define a function that handles this event.

```javascript
handleSelect = (value, geocodedAddress) => {
  // set the current value of the geocoder component, which will change the text in the textbox
  this.setState({ value });

  // now, call the `onSelect` function that you passed in as a prop
  this.props.onSelect(value, geocodedAddress);
}
```
